// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: akka-persistence-fdb.proto

package akka.persistence.foundationdb.serialization;

public final class AkkaPersistenceFdb {
  private AkkaPersistenceFdb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CompactTagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CompactTag)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string persistence_id = 1;</code>
     */
    java.lang.String getPersistenceId();
    /**
     * <code>string persistence_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPersistenceIdBytes();

    /**
     * <code>int64 sequence_nr = 2;</code>
     */
    long getSequenceNr();
  }
  /**
   * Protobuf type {@code CompactTag}
   */
  public  static final class CompactTag extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CompactTag)
      CompactTagOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CompactTag.newBuilder() to construct.
    private CompactTag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CompactTag() {
      persistenceId_ = "";
      sequenceNr_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CompactTag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              persistenceId_ = s;
              break;
            }
            case 16: {

              sequenceNr_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_CompactTag_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_CompactTag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.class, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.Builder.class);
    }

    public static final int PERSISTENCE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object persistenceId_;
    /**
     * <code>string persistence_id = 1;</code>
     */
    public java.lang.String getPersistenceId() {
      java.lang.Object ref = persistenceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        persistenceId_ = s;
        return s;
      }
    }
    /**
     * <code>string persistence_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPersistenceIdBytes() {
      java.lang.Object ref = persistenceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        persistenceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQUENCE_NR_FIELD_NUMBER = 2;
    private long sequenceNr_;
    /**
     * <code>int64 sequence_nr = 2;</code>
     */
    public long getSequenceNr() {
      return sequenceNr_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPersistenceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, persistenceId_);
      }
      if (sequenceNr_ != 0L) {
        output.writeInt64(2, sequenceNr_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPersistenceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, persistenceId_);
      }
      if (sequenceNr_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sequenceNr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag)) {
        return super.equals(obj);
      }
      akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag other = (akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag) obj;

      boolean result = true;
      result = result && getPersistenceId()
          .equals(other.getPersistenceId());
      result = result && (getSequenceNr()
          == other.getSequenceNr());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PERSISTENCE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPersistenceId().hashCode();
      hash = (37 * hash) + SEQUENCE_NR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequenceNr());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CompactTag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CompactTag)
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_CompactTag_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_CompactTag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.class, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.Builder.class);
      }

      // Construct using akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        persistenceId_ = "";

        sequenceNr_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_CompactTag_descriptor;
      }

      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag getDefaultInstanceForType() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.getDefaultInstance();
      }

      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag build() {
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag buildPartial() {
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag result = new akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag(this);
        result.persistenceId_ = persistenceId_;
        result.sequenceNr_ = sequenceNr_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag) {
          return mergeFrom((akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag other) {
        if (other == akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.getDefaultInstance()) return this;
        if (!other.getPersistenceId().isEmpty()) {
          persistenceId_ = other.persistenceId_;
          onChanged();
        }
        if (other.getSequenceNr() != 0L) {
          setSequenceNr(other.getSequenceNr());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object persistenceId_ = "";
      /**
       * <code>string persistence_id = 1;</code>
       */
      public java.lang.String getPersistenceId() {
        java.lang.Object ref = persistenceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          persistenceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string persistence_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPersistenceIdBytes() {
        java.lang.Object ref = persistenceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          persistenceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string persistence_id = 1;</code>
       */
      public Builder setPersistenceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        persistenceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string persistence_id = 1;</code>
       */
      public Builder clearPersistenceId() {
        
        persistenceId_ = getDefaultInstance().getPersistenceId();
        onChanged();
        return this;
      }
      /**
       * <code>string persistence_id = 1;</code>
       */
      public Builder setPersistenceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        persistenceId_ = value;
        onChanged();
        return this;
      }

      private long sequenceNr_ ;
      /**
       * <code>int64 sequence_nr = 2;</code>
       */
      public long getSequenceNr() {
        return sequenceNr_;
      }
      /**
       * <code>int64 sequence_nr = 2;</code>
       */
      public Builder setSequenceNr(long value) {
        
        sequenceNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sequence_nr = 2;</code>
       */
      public Builder clearSequenceNr() {
        
        sequenceNr_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CompactTag)
    }

    // @@protoc_insertion_point(class_scope:CompactTag)
    private static final akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag();
    }

    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompactTag>
        PARSER = new com.google.protobuf.AbstractParser<CompactTag>() {
      public CompactTag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CompactTag(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CompactTag> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompactTag> getParserForType() {
      return PARSER;
    }

    public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RichTagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RichTag)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes payload = 1;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code RichTag}
   */
  public  static final class RichTag extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RichTag)
      RichTagOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RichTag.newBuilder() to construct.
    private RichTag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RichTag() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RichTag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_RichTag_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_RichTag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.class, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.Builder.class);
    }

    public static final int PAYLOAD_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 1;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!payload_.isEmpty()) {
        output.writeBytes(1, payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag)) {
        return super.equals(obj);
      }
      akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag other = (akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag) obj;

      boolean result = true;
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RichTag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RichTag)
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_RichTag_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_RichTag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.class, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.Builder.class);
      }

      // Construct using akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_RichTag_descriptor;
      }

      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag getDefaultInstanceForType() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.getDefaultInstance();
      }

      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag build() {
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag buildPartial() {
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag result = new akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag(this);
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag) {
          return mergeFrom((akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag other) {
        if (other == akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.getDefaultInstance()) return this;
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 1;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 1;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 1;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RichTag)
    }

    // @@protoc_insertion_point(class_scope:RichTag)
    private static final akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag();
    }

    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RichTag>
        PARSER = new com.google.protobuf.AbstractParser<RichTag>() {
      public RichTag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RichTag(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RichTag> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RichTag> getParserForType() {
      return PARSER;
    }

    public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Tag)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CompactTag compact = 1;</code>
     */
    boolean hasCompact();
    /**
     * <code>.CompactTag compact = 1;</code>
     */
    akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag getCompact();
    /**
     * <code>.CompactTag compact = 1;</code>
     */
    akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTagOrBuilder getCompactOrBuilder();

    /**
     * <code>.RichTag rich = 2;</code>
     */
    boolean hasRich();
    /**
     * <code>.RichTag rich = 2;</code>
     */
    akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag getRich();
    /**
     * <code>.RichTag rich = 2;</code>
     */
    akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTagOrBuilder getRichOrBuilder();
  }
  /**
   * Protobuf type {@code Tag}
   */
  public  static final class Tag extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Tag)
      TagOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tag.newBuilder() to construct.
    private Tag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tag() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.Builder subBuilder = null;
              if (compact_ != null) {
                subBuilder = compact_.toBuilder();
              }
              compact_ = input.readMessage(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(compact_);
                compact_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.Builder subBuilder = null;
              if (rich_ != null) {
                subBuilder = rich_.toBuilder();
              }
              rich_ = input.readMessage(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rich_);
                rich_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_Tag_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_Tag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag.class, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag.Builder.class);
    }

    public static final int COMPACT_FIELD_NUMBER = 1;
    private akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag compact_;
    /**
     * <code>.CompactTag compact = 1;</code>
     */
    public boolean hasCompact() {
      return compact_ != null;
    }
    /**
     * <code>.CompactTag compact = 1;</code>
     */
    public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag getCompact() {
      return compact_ == null ? akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.getDefaultInstance() : compact_;
    }
    /**
     * <code>.CompactTag compact = 1;</code>
     */
    public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTagOrBuilder getCompactOrBuilder() {
      return getCompact();
    }

    public static final int RICH_FIELD_NUMBER = 2;
    private akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag rich_;
    /**
     * <code>.RichTag rich = 2;</code>
     */
    public boolean hasRich() {
      return rich_ != null;
    }
    /**
     * <code>.RichTag rich = 2;</code>
     */
    public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag getRich() {
      return rich_ == null ? akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.getDefaultInstance() : rich_;
    }
    /**
     * <code>.RichTag rich = 2;</code>
     */
    public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTagOrBuilder getRichOrBuilder() {
      return getRich();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (compact_ != null) {
        output.writeMessage(1, getCompact());
      }
      if (rich_ != null) {
        output.writeMessage(2, getRich());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (compact_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCompact());
      }
      if (rich_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRich());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag)) {
        return super.equals(obj);
      }
      akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag other = (akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag) obj;

      boolean result = true;
      result = result && (hasCompact() == other.hasCompact());
      if (hasCompact()) {
        result = result && getCompact()
            .equals(other.getCompact());
      }
      result = result && (hasRich() == other.hasRich());
      if (hasRich()) {
        result = result && getRich()
            .equals(other.getRich());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCompact()) {
        hash = (37 * hash) + COMPACT_FIELD_NUMBER;
        hash = (53 * hash) + getCompact().hashCode();
      }
      if (hasRich()) {
        hash = (37 * hash) + RICH_FIELD_NUMBER;
        hash = (53 * hash) + getRich().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Tag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Tag)
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.TagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_Tag_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_Tag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag.class, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag.Builder.class);
      }

      // Construct using akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (compactBuilder_ == null) {
          compact_ = null;
        } else {
          compact_ = null;
          compactBuilder_ = null;
        }
        if (richBuilder_ == null) {
          rich_ = null;
        } else {
          rich_ = null;
          richBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.internal_static_Tag_descriptor;
      }

      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag getDefaultInstanceForType() {
        return akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag.getDefaultInstance();
      }

      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag build() {
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag buildPartial() {
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag result = new akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag(this);
        if (compactBuilder_ == null) {
          result.compact_ = compact_;
        } else {
          result.compact_ = compactBuilder_.build();
        }
        if (richBuilder_ == null) {
          result.rich_ = rich_;
        } else {
          result.rich_ = richBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag) {
          return mergeFrom((akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag other) {
        if (other == akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag.getDefaultInstance()) return this;
        if (other.hasCompact()) {
          mergeCompact(other.getCompact());
        }
        if (other.hasRich()) {
          mergeRich(other.getRich());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag compact_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.Builder, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTagOrBuilder> compactBuilder_;
      /**
       * <code>.CompactTag compact = 1;</code>
       */
      public boolean hasCompact() {
        return compactBuilder_ != null || compact_ != null;
      }
      /**
       * <code>.CompactTag compact = 1;</code>
       */
      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag getCompact() {
        if (compactBuilder_ == null) {
          return compact_ == null ? akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.getDefaultInstance() : compact_;
        } else {
          return compactBuilder_.getMessage();
        }
      }
      /**
       * <code>.CompactTag compact = 1;</code>
       */
      public Builder setCompact(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag value) {
        if (compactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          compact_ = value;
          onChanged();
        } else {
          compactBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CompactTag compact = 1;</code>
       */
      public Builder setCompact(
          akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.Builder builderForValue) {
        if (compactBuilder_ == null) {
          compact_ = builderForValue.build();
          onChanged();
        } else {
          compactBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CompactTag compact = 1;</code>
       */
      public Builder mergeCompact(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag value) {
        if (compactBuilder_ == null) {
          if (compact_ != null) {
            compact_ =
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.newBuilder(compact_).mergeFrom(value).buildPartial();
          } else {
            compact_ = value;
          }
          onChanged();
        } else {
          compactBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CompactTag compact = 1;</code>
       */
      public Builder clearCompact() {
        if (compactBuilder_ == null) {
          compact_ = null;
          onChanged();
        } else {
          compact_ = null;
          compactBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CompactTag compact = 1;</code>
       */
      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.Builder getCompactBuilder() {
        
        onChanged();
        return getCompactFieldBuilder().getBuilder();
      }
      /**
       * <code>.CompactTag compact = 1;</code>
       */
      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTagOrBuilder getCompactOrBuilder() {
        if (compactBuilder_ != null) {
          return compactBuilder_.getMessageOrBuilder();
        } else {
          return compact_ == null ?
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.getDefaultInstance() : compact_;
        }
      }
      /**
       * <code>.CompactTag compact = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.Builder, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTagOrBuilder> 
          getCompactFieldBuilder() {
        if (compactBuilder_ == null) {
          compactBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTag.Builder, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.CompactTagOrBuilder>(
                  getCompact(),
                  getParentForChildren(),
                  isClean());
          compact_ = null;
        }
        return compactBuilder_;
      }

      private akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag rich_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.Builder, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTagOrBuilder> richBuilder_;
      /**
       * <code>.RichTag rich = 2;</code>
       */
      public boolean hasRich() {
        return richBuilder_ != null || rich_ != null;
      }
      /**
       * <code>.RichTag rich = 2;</code>
       */
      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag getRich() {
        if (richBuilder_ == null) {
          return rich_ == null ? akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.getDefaultInstance() : rich_;
        } else {
          return richBuilder_.getMessage();
        }
      }
      /**
       * <code>.RichTag rich = 2;</code>
       */
      public Builder setRich(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag value) {
        if (richBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rich_ = value;
          onChanged();
        } else {
          richBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RichTag rich = 2;</code>
       */
      public Builder setRich(
          akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.Builder builderForValue) {
        if (richBuilder_ == null) {
          rich_ = builderForValue.build();
          onChanged();
        } else {
          richBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RichTag rich = 2;</code>
       */
      public Builder mergeRich(akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag value) {
        if (richBuilder_ == null) {
          if (rich_ != null) {
            rich_ =
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.newBuilder(rich_).mergeFrom(value).buildPartial();
          } else {
            rich_ = value;
          }
          onChanged();
        } else {
          richBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RichTag rich = 2;</code>
       */
      public Builder clearRich() {
        if (richBuilder_ == null) {
          rich_ = null;
          onChanged();
        } else {
          rich_ = null;
          richBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RichTag rich = 2;</code>
       */
      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.Builder getRichBuilder() {
        
        onChanged();
        return getRichFieldBuilder().getBuilder();
      }
      /**
       * <code>.RichTag rich = 2;</code>
       */
      public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTagOrBuilder getRichOrBuilder() {
        if (richBuilder_ != null) {
          return richBuilder_.getMessageOrBuilder();
        } else {
          return rich_ == null ?
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.getDefaultInstance() : rich_;
        }
      }
      /**
       * <code>.RichTag rich = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.Builder, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTagOrBuilder> 
          getRichFieldBuilder() {
        if (richBuilder_ == null) {
          richBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTag.Builder, akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.RichTagOrBuilder>(
                  getRich(),
                  getParentForChildren(),
                  isClean());
          rich_ = null;
        }
        return richBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Tag)
    }

    // @@protoc_insertion_point(class_scope:Tag)
    private static final akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag();
    }

    public static akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tag>
        PARSER = new com.google.protobuf.AbstractParser<Tag>() {
      public Tag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tag(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tag> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tag> getParserForType() {
      return PARSER;
    }

    public akka.persistence.foundationdb.serialization.AkkaPersistenceFdb.Tag getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CompactTag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CompactTag_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RichTag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RichTag_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tag_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032akka-persistence-fdb.proto\"9\n\nCompactT" +
      "ag\022\026\n\016persistence_id\030\001 \001(\t\022\023\n\013sequence_n" +
      "r\030\002 \001(\003\"\032\n\007RichTag\022\017\n\007payload\030\001 \001(\014\";\n\003T" +
      "ag\022\034\n\007compact\030\001 \001(\0132\013.CompactTag\022\026\n\004rich" +
      "\030\002 \001(\0132\010.RichTagB-\n+akka.persistence.fou" +
      "ndationdb.serializationb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CompactTag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CompactTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CompactTag_descriptor,
        new java.lang.String[] { "PersistenceId", "SequenceNr", });
    internal_static_RichTag_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RichTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RichTag_descriptor,
        new java.lang.String[] { "Payload", });
    internal_static_Tag_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Tag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tag_descriptor,
        new java.lang.String[] { "Compact", "Rich", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
